### ISSUE TITLE
Error after upgrading (ENOENT: no such file or directory ...)

### ISSUE THREAD

**Issue by whoisjorge** [nuxt-community/svg-sprite-module#124]
Howdy! After updating to the latest version, it happens something similar to #120.

My dev output is:
```sh
 ERROR  ENOENT: no such file or directory, open '.../nuxt-application/.nuxt/nuxt-svg-sprite-icons-list.vue'

  at Object.openSync (fs.js:440:3)
  at readFileSync (fs.js:342:35)
  at exports.extractComponentOptions (node_modules/nuxt-i18n/src/helpers/components.js:12:45)
  at buildLocalizedRoutes (node_modules/nuxt-i18n/src/helpers/routes.js:31:21)
  at exports.makeRoutes (node_modules/nuxt-i18n/src/helpers/routes.js:135:46)
  at Object.<anonymous> (node_modules/nuxt-i18n/src/index.js:68:33)
  at Object.extendRoutes (node_modules/@nuxt/utils/dist/utils.js:1817:17)
  at Builder.resolveRoutes (node_modules/@nuxt/builder/dist/builder.js:5836:50)
  at async Promise.all (index 1)
  at async Builder.generateRoutesAndFiles (node_modules/@nuxt/builder/dist/builder.js:5664:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:5589:5)
  at async Object._buildDev (node_modules/@nuxt/cli/dist/cli-dev.js:98:5)
  at async Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:56:7)
  at async Object.onWatchRestart (node_modules/@nuxt/cli/dist/cli-dev.js:122:5)
  at async Nuxt.callHook (node_modules/hable/lib/hookable.js:50:7)
  at async FSWatcher.<anonymous> (node_modules/@nuxt/builder/dist/builder.js:6172:9)
```
I am using  **nuxt** `2.10.2` and **nuxt-i18n** `6.4.1` and my setup is very straightforward (It works perfectly with `<= 0.3.0`😕):

**nuxt.config.js**
```js
  buildModules: [
    ['@nuxtjs/svg-sprite', {
      input: '~/assets/svg/',
      output: '~/assets/svg/generated/'
    }]
  ],
```

**Comment by farnabaz** [comment]
This should be fixed in version 0.4.7, feel free to reopen this issue if Error still exists

**Comment by whoisjorge** [comment]
I upgraded to 0.4.7 and I'm still having the same issue. It may be something related to `nuxt-i18n` since it works perfectly after removing the i18n nuxt module from the `nuxt.config.js` 😕

**Comment by sectsect** [comment]
I have same problem.

**Comment by andrewvasilchuk** [comment]
@farnabaz getting the same issue

**Comment by farnabaz** [comment]
This is related to `nuxt-i18n` and its special way to load components, move `@nuxtjs/svg-sprite` after `nuxt-i18n`. https://github.com/nuxt-community/svg-sprite-module/issues/120#issuecomment-567258319

```
{
...
modules: [
  ...
  'nuxt-i18n',
  '@nuxtjs/svg-sprite',
  ...
]
...
}
```

**Comment by andrewvasilchuk** [comment]
@farnabaz, thanks for the quick response 👍

**Comment by reinoldus** [comment]
I keep hitting this error even after moving svg-sprite. 

I checked out a fresh nuxt instance on my machine and that seems to work. Anyone got a hint where I should look?

Tried to uncomment all modules except i18n and svg-sprite, but I keep hitting this error

**Comment by AlexisWalravens** [comment]
I have currently the same issue, changing the order of nuxt-i18n doesn't make any difference.

 Nuxt: 2.14.1
@nuxtjs/svg-sprite: 0.4.11

**Comment by farnabaz** [comment]
This issue is fixed in https://github.com/nuxt-community/svg-sprite-module/pull/184 and will publish in [next release](https://github.com/nuxt-community/svg-sprite-module/pull/187).
